config/routes.rb
Rails.application.routes.draw do
  # static home page
  root to: 'pages#show', id: 'index'
  # using high_voltage for static pages
  get '/pages/*id' => 'pages#show', as: :page, format: false

  # products controller with repository pattern
  resources :products do
    patch 'reorder', on: :member
  end

  # products controller with fat model
  resources :inventories do
    patch 'reorder', on: :member
  end
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :inventory_reorders

  validates :sku, :name, :stock, presence: true

  # register custom validation
  validate :only_one_active_reorder

  # validation method to only allow a single reorder to be active
  def only_one_active_reorder
    return unless inventory_reorders && inventory_reorders.active.count > 1
    errors.add(:inventory_reorders, 'Cannot have more than a single active reorder')
  end

  # is stock low enough to require a reorder
  def reorder_stock?
    stock < 100 && !current_reorder ? true : false
  end

  # determine which reorder date to use
  def reorder_date
    # todo move out field prioritizationa and selection to module
    return nil unless current_reorder
    current_reorder.delivery_date ? current_reorder.delivery_date : current_reorder.estimated_delivery_date
  end

  # find latest active order
  def current_reorder
    inventory_reorders.active.first
  end

  # create a new reorder if < 100 stock
  def create_reorder
    return nil unless stock < 100
    return nil if current_reorder
    reorder = InventoryReorder.new(status: 'active', quantity: (1000 - stock), estimated_delivery_date: create_default_estimated_date)
    inventory_reorders << reorder
    reorder if save
  end

  # report reorders by active/other status then last updated descending
  def reorder_report
    report = inventory_reorders.report_order
    report.count > 0 ? report : nil
  end

  # logic for a new estimated date is today + 7
  def create_default_estimated_date
    Date.today + 7
  end

end

app/models/inventory_reorder.rb
class InventoryReorder < ActiveRecord::Base

  validates :quantity, :estimated_delivery_date, :status,  presence: true

  scope :active, -> { where(status: :active) }

  scope :report_order, -> { order(status: :asc, updated_at: :desc) }
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_reorders

  # register custom validation
  validate :only_one_active_reorder

  validates :sku, :name, :stock, presence: true

  # validation method to only allow a single reorder to be active
  def only_one_active_reorder
    return unless product_reorders && product_reorders.active.count > 1
    errors.add(:product_reorders, 'Cannot have more than a single active reorder')
  end
end

app/models/product_reorder.rb
class ProductReorder < ActiveRecord::Base
  validates :quantity, :estimated_delivery_date, :status,  presence: true

  scope :active, -> { where(status: :active) }

  scope :report_order, -> { order(status: :asc, updated_at: :desc) }
end

app/models/reorder.rb
class Reorder < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy, :reorder]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PATCH /inventories/1/reorder
  # PATCH /inventories/1/reorder.json
  def reorder
    respond_to do |format|
      if @inventory.create_reorder
        format.html { redirect_to @inventory, notice: 'Inventory was successfully reordered.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { redirect_to @inventory, alert: 'Could not reorder' }
        format.json { render json: 'Could not reorder', status: :unprocessable_entity }
      end
    end
  end

  private

  def set_inventory
    @inventory = Inventory.find(params[:id])
  end

  def inventory_params
    params.require(:inventory).permit(:name, :sku, :blurb, :stock)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage
  layout 'static_pages'
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include SbbHexagonal::RepositoryAdapter
  before_action :set_product, only: [:show, :edit, :update, :destroy, :reorder]
  before_action :set_repository

  # GET /products
  # GET /products.json
  def index
    @products = repo.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = repo.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = repo.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PATCH /products/1/reorder
  # PATCH /products/1/reorder.json
  def reorder
    respond_to do |format|
      if repo.create_reorder(@product)
        format.html { redirect_to @product, notice: 'Product was successfully reordered.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { redirect_to @product, alert: 'Could not reorder' }
        format.json { render json: 'Could not reorder', status: :unprocessable_entity }
      end
    end
  end

  private

  def set_product
    @product = repo.find(params[:id])
  end

  def set_repository
    @repository = repo
  end

  def product_params
    params.require(:product).permit(:name, :sku, :blurb, :stock)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :sku %>
    <%= f.text_field :sku, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :stock %>
    <%= f.text_field :stock, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :blurb %>
    <%= f.text_field :blurb, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<% content_for :titles do %>
  Editing Product <%= @inventory.id %>
<% end %>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<% content_for :titles do %>
  Inventory List
<% end %>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Id</th>
    <th>Sku</th>
    <th>Name</th>
    <th>Stock</th>
    <th>Reorder</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @inventories.each do |inventory| %>
    <tr>
      <td><%= inventory.id %></td>
      <td><%= inventory.sku %></td>
      <td><%= inventory.name %></td>
      <td><%= inventory.stock %></td>
      <% if inventory.reorder_stock? %>
        <td><%= link_to 'Reorder', reorder_inventory_path(inventory), method: :patch %></td>
      <% elsif inventory.reorder_date %>
        <td><%= inventory.reorder_date %></td>
      <% else %>
      <td></td>
      <% end %>
      <td><%= link_to 'Show', inventory %></td>
      <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
      <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_inventory_path %>

app/views/inventories/new.html.erb
<% content_for :titles do %>
  New Product
<% end %>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<% content_for :titles do %>
  Product <%= @inventory.id %>
<% end %>
<div>Sku: <%= @inventory.sku %></div>
<div>Name: <%= @inventory.name %></div>
<div>Stock: <%= @inventory.stock %></div>
<div>Blurb: <%= @inventory.blurb %></div>
<!-- if we have an active reorder what is the date -->
<% if @inventory.reorder_date %>
  <div>Reorder delivery date: <%= @inventory.reorder_date %></div>
<% end %>
<br>

<!-- if there is no active reorder and the product stock is less than 100 items show reorder button -->
<% if @inventory.reorder_stock? %>
  <div><%= button_to 'Reorder', reorder_inventory_path(@inventory), method: :patch, class: 'btn btn-primary' %></div>
<% end %>

<!-- if there are reorders show a sub table -->

<% if @inventory.reorder_report %>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Status</th>
      <th>Quantity</th>
      <th>Estimated Delivery Date</th>
      <th>Delivery Date</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @inventory.reorder_report.each do |reorder| %>
      <tr>
        <td><%= reorder.status %></td>
        <td><%= reorder.quantity %></td>
        <td><%= reorder.estimated_delivery_date %></td>
        <td><%= reorder.delivery_date %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<br>
<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SbbHexagonalDemos</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="robots" content="noindex, nofollow"/>
  <meta name="description" content="Test bed for demos"/>
  <meta name="keywords" content="rails ruby activemodel"/>
</head>
<body role="document">
<!-- Navigation -->
<%= render 'shared/top_nav' %>

<!-- page title -->

<!-- content section a -->
<div class="content-section-a">


  <div class="clearfix"></div>
  <div class="container"><h2 class="section-heading"><%= content_for(:titles) -%></h2></div>
  <!-- errors block -->
  <div class="container">
    <% if notice %>
      <div class="row">
        <div>
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= notice %>
          </div>
        </div>
      </div>
    <% end %>
    <% if alert %>
      <div class="row">
        <div>
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= alert %>
          </div>
        </div>
      </div>
    <% end %>
  </div>


  <div class="container">
    <%= yield %>
  </div>
  <!-- /.container -->

</div>
<!-- end content section a -->





<!-- Footer -->
<%= render 'shared/footer' %>

</body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SbbHexagonalDemos</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="robots" content="noindex, nofollow"/>
  <meta name="description" content="Test bed for demos"/>
  <meta name="keywords" content="rails ruby activemodel"/>
</head>
<body role="document">
<!-- Navigation -->
<%= render 'shared/top_nav' %>


<%= yield %>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <ul class="list-inline">
            <li>
              <a href="#">Home</a>
            </li>
            <li class="footer-menu-divider">&sdot;</li>
            <li>
              <a href="#about">About</a>
            </li>
            <li class="footer-menu-divider">&sdot;</li>
            <li>
              <a href="#services">Services</a>
            </li>
            <li class="footer-menu-divider">&sdot;</li>
            <li>
              <a href="#contact">Contact</a>
            </li>
          </ul>
          <p class="copyright text-muted small">Copyright &copy; SBB Systems 2015. All Rights Reserved</p>
          <p class="copyright text-muted small">Image by sippakorn at FreeDigitalPhotos.net</p>
          <p class="copyright text-muted small">Bootstrap theme by <%= link_to 'Start Bootstrap', 'http://startbootstrap.com/', target: '_blank' %></p>


        </div>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/pages/index.html.erb
<!-- Header -->
<a name="about"></a>
<div class="intro-header">
  <div class="container">

    <div class="row">
      <div class="col-lg-12">
        <div class="intro-message">
          <h1>Hexagonal Examples</h1>

          <h3>SBB Software, sometimes interesting</h3>
          <hr class="intro-divider">
          <ul class="list-inline intro-social-buttons">
            <li>
              <a href="http://www.sbbsoftware.com" class="btn btn-default btn-lg"><i class="fa fa-chevron-circle-right fa-fw"></i>
                <span class="network-name">si by sbb</span></a>
            </li>
            <li>
              <a href="https://twitter.com/spc9999" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i>
                <span class="network-name">Twitter</span></a>
            </li>
            <li>
              <a href="https://github.com/SBBSoftware" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i>
                <span class="network-name">Github</span></a>
            </li>

          </ul>
        </div>
      </div>
    </div>

  </div>
  <!-- /.container -->

</div>
<!-- /.intro-header -->

<!-- Page Content -->
<!-- /.content-section-a -->

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :sku %>
    <%= f.text_field :sku, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :stock %>
    <%= f.text_field :stock, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :blurb %>
    <%= f.text_field :blurb, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% content_for :titles do %>
  Editing Product <%= @product.id %>
<% end %>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% content_for :titles do %>
  Product List
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Sku</th>
      <th>Name</th>
      <th>Stock</th>
      <th>Reorder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.sku %></td>
        <td><%= product.name %></td>
        <td><%= product.stock %></td>
        <% if @repository.reorder_stock?(product) %>
          <td><%= link_to 'Reorder', reorder_product_path(product), method: :patch %></td>
        <% elsif @repository.reorder_date(product) %>
          <td><%= @repository.reorder_date(product) %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<% content_for :titles do %>
  New Product
<% end %>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% content_for :titles do %>
  Product <%= @product.id %>
<% end %>
<div>Sku: <%= @product.sku %></div>
<div>Name: <%= @product.name %></div>
<div>Stock: <%= @product.stock %></div>
<div>Blurb: <%= @product.blurb %></div>
<!-- if we have an active reorder what is the date -->
<% if @repository.reorder_date(@product) %>
  <div>Reorder delivery date: <%= @repository.reorder_date(@product) %></div>
<% end %>
<br>

<!-- if there is no active reorder and the product stock is less than 100 items show reorder button -->
<% if @repository.reorder_stock?(@product) %>
  <div><%= button_to 'Reorder', reorder_product_path(@product), method: :patch, class: 'btn btn-primary' %></div>
<% end %>

<!-- if there are reorders show a sub table -->

<% if @repository.reorder_report(@product) %>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Status</th>
      <th>Quantity</th>
      <th>Estimated Delivery Date</th>
      <th>Delivery Date</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @repository.reorder_report(@product).each do |reorder| %>
      <tr>
        <td><%= reorder.status %></td>
        <td><%= reorder.quantity %></td>
        <td><%= reorder.estimated_delivery_date %></td>
        <td><%= reorder.delivery_date %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<br>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_footer.html.erb
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<div class="banner">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <h2>Connect to SBB Systems</h2>
      </div>
      <div class="col-lg-6">
        <ul class="list-inline banner-social-buttons">
          <li>
            <a href="http://www.sbbsoftware.com" class="btn btn-default btn-lg"><i class="fa fa-chevron-circle-right fa-fw"></i>
              <span class="network-name">si by sbb</span></a>
          </li>
          <li>
            <a href="https://twitter.com/spc9999" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i>
              <span class="network-name">Twitter</span></a>
          </li>
          <li>
            <a href="https://github.com/SBBSoftware" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i>
              <span class="network-name">Github</span></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- /.banner -->

app/views/shared/_top_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
  <div class="container topnav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand topnav' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Fat Product Demo', inventories_path %></li>
        <li><%= link_to 'Product Repo Demo', products_path %></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>